describe('Record',() => {
    it('Test1', () => {
        /* ==== Generated with Cypress Studio ==== */
        cy.visit('localhost:8100/home');
        cy.get('#login-btn-ir-a-crear-cuenta').click();
        cy.get('#ion-input-2').clear('te');
        cy.get('#ion-input-2').type('testuser@example.com');
        cy.get('#ion-input-3').clear();
        cy.get('#ion-input-3').type('password123');
        cy.get('#signup-btn-crear-cuenta').click();
        cy.get('#login-input-email > .input-wrapper > .native-wrapper').click();
        cy.get('#ion-input-0').clear('te');
        cy.get('#ion-input-0').type('testuser@example.com');
        cy.get('#ion-input-1').clear();
        cy.get('#ion-input-1').type('password123');
        cy.get('#login-btn-iniciar-sesion').click();
        cy.get('.can-go-back > .content-ltr').click();
        cy.get('#todo-task-6').click();
        cy.get('#todo-task-6 > ion-card-header.ion-inherit-color > .ion-inherit-color').click();
        cy.get('#todo-add-task > .md').click();
        cy.get('#ion-textarea-0').click();
        cy.get('#taskPriority').click();
        cy.get('#taskPriority').click();
        cy.get('#alert-input-5-0 > .alert-button-inner > .alert-radio-label').click();
        cy.get('ion-backdrop.sc-ion-alert-md').click();
        cy.get('ion-datetime-button.ion-color').click();
        cy.get('#datetime').click();
        cy.get('#ion-overlay-3').click();
        cy.get('.date-active').click();
        cy.get('#datetime').click();
        cy.get('#ion-overlay-3').click();
        cy.get(':nth-child(5) > :nth-child(3) > .sc-ion-label-md-h').click();
        cy.get('#addTaskButton').click();
        cy.get('.can-go-back > .header-md > ion-toolbar.md > .buttons-first-slot > .sc-ion-buttons-md').click();
        cy.get('#week-item > .sc-ion-label-md-h').click();
        cy.get('app-week.ion-page > .header-md > ion-toolbar.md > .buttons-first-slot > #menu-button').click();
        cy.get('#memories-item').click();
        cy.get('#thumbnail-image-1').click();
        cy.get('.buttons-last-slot > :nth-child(1)').click();
        cy.get('.ion-page > .header-md > .toolbar-title-default > .buttons-first-slot > .button').click();
        cy.get('#thumbnail-image-8').click();
        cy.get('.buttons-last-slot > :nth-child(2)').click();
        cy.get('#fab-button').click();
        cy.get('pwa-action-sheet.hydrated').click();
        cy.get('pwa-camera-modal-instance.hydrated').click();
        cy.get('pwa-camera-modal-instance.hydrated').click();
        cy.get('#fab-button > .md').click();
        cy.get('pwa-action-sheet.hydrated').click();
        cy.get('app-memories.ion-page > .header-md > ion-toolbar.md > .buttons-first-slot > #menu-button').click();
        cy.get('#archive-item > .sc-ion-label-md-h').click();
        cy.get('app-archive.ion-page > .header-md > ion-toolbar.md > .buttons-first-slot > #menu-button').click();
        cy.get('#todo-item > .sc-ion-label-md-h').click();
        cy.get('#todo-edit-task-0 > p').click();
        cy.get('#ion-input-4').clear('Task 1 ');
        cy.get('#ion-input-4').type('Task 1 editado');
        cy.get('#taskPriority').click();
        cy.get('#taskPriority').click();
        cy.get('#alert-input-17-1 > .alert-button-inner > .alert-radio-label').click();
        cy.get('ion-backdrop.sc-ion-alert-md').click();
        cy.get('.card-content-md > .item-has-start-slot > .sc-ion-label-md-h').click();
        cy.get('.card-content-md > .button').click();
        cy.get('#todo-delete-task-5 > p').click();
        cy.get('.can-go-back > .header-md > ion-toolbar.md > .buttons-first-slot > .sc-ion-buttons-md').click();
        cy.get('#login-item > .sc-ion-label-md-h').click();
        /* ==== End Cypress Studio ==== */
    })

    /* ==== Test Created with Cypress Studio ==== */
    it('testing 2', function() {
        /* ==== Generated with Cypress Studio ==== */
        cy.visit('localhost:8100/home');
        cy.get('#ion-input-0').click();
        cy.get('#login-btn-ir-a-crear-cuenta').click();
        cy.get('#signup-input-email > .input-wrapper > .native-wrapper').click();
        cy.get('#ion-input-2').click();
        cy.get('#ion-input-2').clear('te');
        cy.get('#ion-input-2').type('testuser@example.com');
        cy.get('#ion-input-3').clear('p');
        cy.get('#ion-input-3').type('password123');
        cy.get('#signup-btn-crear-cuenta').click();
        cy.get('#ion-input-0').clear('te');
        cy.get('#ion-input-0').type('testuser@example.com');
        cy.get('#ion-input-1').clear();
        cy.get('#ion-input-1').type('password123');
        cy.get('#ion-input-1').click();
        cy.get('#ion-input-1').click();
        cy.get('#ion-input-1').click();
        cy.get('#ion-input-1').clear('p');
        cy.get('#ion-input-1').type('password123');
        cy.get('#login-btn-iniciar-sesion').click();
        cy.get('#todo-task-4 > ion-card-header.ion-inherit-color > .ion-inherit-color > .item').click();
        cy.get('#todo-task-4 > ion-card-header.ion-inherit-color > .ion-inherit-color > .item > .sc-ion-label-md-h').click();
        cy.get('#todo-add-task > .md').click();
        cy.get('#ion-textarea-0').click();
        cy.get('#taskPriority').click();
        cy.get('#taskPriority').click();
        cy.get('#alert-input-5-1 > .alert-button-inner > .alert-radio-label').click();
        cy.get('.alert-button-group > :nth-child(2) > .alert-button-inner').click();
        cy.get('ion-datetime-button.ion-color').click();
        cy.get('#datetime').click();
        cy.get('#ion-overlay-3').click();
        cy.get('.date-active').click();
        cy.get('#datetime').click();
        cy.get('#ion-overlay-3').click();
        cy.get('ion-card.md > :nth-child(5) > :nth-child(3)').click();
        cy.get('#addTaskButton').click();
        cy.get('.can-go-back > .header-md > ion-toolbar.md > .buttons-first-slot > .sc-ion-buttons-md').click();
        cy.get('#week-item').click();
        cy.get('app-week.ion-page > .header-md > ion-toolbar.md > .buttons-first-slot > #menu-button').click();
        cy.get('#archive-item > .sc-ion-label-md-h').click();
        cy.get('app-archive.ion-page > .header-md > ion-toolbar.md > .buttons-first-slot > #menu-button').click();
        cy.get('#memories-item > .sc-ion-label-md-h').click();
        cy.get('#thumbnail-image-1').click();
        cy.get('.buttons-last-slot > :nth-child(1)').click();
        cy.get('.ion-page > .header-md > .toolbar-title-default > .buttons-first-slot > .button').click();
        cy.get('#thumbnail-image-8').click();
        cy.get('.buttons-last-slot > :nth-child(2)').click();
        cy.get('#fab-button > .md').click();
        cy.get('pwa-action-sheet.hydrated').click();
        cy.get('pwa-camera-modal-instance.hydrated').click();
        cy.get('pwa-camera-modal-instance.hydrated').click();
        cy.get('app-memories.ion-page > .header-md > ion-toolbar.md > .buttons-first-slot > #menu-button').click();
        cy.get('#todo-item > .sc-ion-label-md-h').click();
        cy.get('#todo-delete-task-0 > p').click();
        cy.get('#todo-edit-task-1 > .md').click();
        cy.get('#ion-input-4').clear('Task 2: Videof');
        cy.get('#ion-input-4').type('Task 2: Videoffff');
        cy.get('.card-content-md > .button').click();
        cy.get('#todo-complete-task-2 > p').click();
        /* ==== End Cypress Studio ==== */
    });
})